import './globals.css'
import { Sora} from 'next/font/google'
import Header from "@/app/components/Header";

const inter = Sora({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      {children}</body>
    </html>
  )
}
