import './globals.css'
import {Sora} from 'next/font/google'
import Header from "@/app/components/Header";
import {Providers} from "@/app/GlobalRedux/provider";

const inter = Sora({subsets: ['latin']})

export const metadata = {
    title: 'Upview React Task',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>

        <Providers>
            <Header/>

            {children}
        </Providers>


        </body>
        </html>
    )
}
